---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: proxy
    templates:
    - name: nginx
    instances: 2
    persitent_disk: 0
    resource_pool: small_z1
    networks: (( param "Please configure the networks for this job" ))

  - name: fubar
    templates:
    - name: fubar
      release: fubar
    instances: 2
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "Please configure the networks for this job" ))

networks: (( param "Please configure the global network definitions for this Deployment" ))

properties:
  fubar:
    port: 8080
  nginx:
    port: 1234
    backend_servers: (( grab jobs.proxy.networks.fubar1.static_ips ))
    backend_port: (( grab properties.fubar.port ))
